Make sure all Wikibase codebases run PHPCS during `composer test`
wmde/WikibaseInternalSerialization pull request #136
Opened 2021-04-28 14:24 UTC by bereket-WMDE

Bug: [T188395](https://phabricator.wikimedia.org/T188395)

2021-04-28 15:13 UTC, JeroenDeDauw commented
Boo. https://phabricator.wikimedia.org/T188395#4651556

2021-04-29 09:38 UTC, tzhelyazkova requested changes
the `@cs` command should be removed from the `ci` script to avoid running it twice (since it's part of `test` now)

2021-04-29 09:38 UTC, tzhelyazkova commented on composer.json
> +			"composer cs",
this can alternatively be `@cs`

2021-04-29 11:03 UTC, bereket-WMDE commented on composer.json
> +			"composer cs",
thanks. I updated the changes

2021-05-03 13:38 UTC, merged